# Generated by Django 4.2.3 on 2023-07-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesknees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DExercise_board',
        ),
    ]
