# Generated by Django 4.2.3 on 2023-07-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beesknees', '0002_exercises_delete_dexercise_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
    ]
