# Generated by Django 4.2.3 on 2023-07-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beesknees', '0004_exercise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
    ]
