# Generated by Django 4.2.3 on 2023-07-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesknees', '0005_remove_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.URLField(),
        ),
    ]
